apiVersion: v1
kind: ReplicationController
metadata:
  name: echo-server-rc
spec:
  replicas: 3
  selector:
    app-name: echo-server-app
  template:
    metadata:
      labels:
         app-name: echo-server-app
    spec:     
      containers:
      - image: landrzejewski/echo-server:v1
        name: echo-server
        ports:
        - containerPort: 8080
