apiVersion: v1
kind: PersistentVolume
metadata:
  name: training-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  #persistentVolumeReclaimPolicy: Recycle
  flexVolume:
    driver: ceph.rook.io/rook
    fsType: ceph
    options:
      fsName: training-fs
      clusterNamespace: rook-ceph
      ##path: /training
