apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: Pod
metadata:
  name: updater-po
spec:
  containers:
    - name: updater
      image: landrzejewski/updater:v1
      volumeMounts:
        - mountPath: /var/htdocs
          name: storage
    - name: web-server
      image: nginx:1.17.3-alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: storage
      ports:
        - containerPort: 80
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: share-claim