apiVersion: v1
kind: ConfigMap
metadata:
  name: base
data:
  CONFIGURATION_SERVER: configuration-service
  CONFIGURATION_SERVER_PORT: '8888'
  KAFKA_SERVER: kafka-service
  KAFKA_PORT: '9092'
  SLEEP_TIME: '1'
  DEFAULT_PROFILE: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: zookeeper
  template:
    metadata:
      labels:
        app-name: zookeeper
    spec:
      containers:
        - image: wurstmeister/zookeeper
          name: zookeeper
          ports:
            - containerPort: 2181
              name: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app-name: zookeeper
  ports:
    - port: 2181
      targetPort: zookeeper
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka
data:
  KAFKA_ADVERTISED_HOST_NAME: kafka-service
  KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: kafka
  template:
    metadata:
      labels:
        app-name: kafka
    spec:
      containers:
        - image: wurstmeister/kafka
          name: kafka
          envFrom:
            - configMapRef:
                name: kafka
          ports:
            - containerPort: 9092
              name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app-name: kafka
  ports:
    - port: 9092
      targetPort: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration
spec:
  replicas: 3
  selector:
    matchLabels:
      app-name: configuration
  template:
    metadata:
      labels:
        app-name: configuration
    spec:
      containers:
        - name: configuration
          image: landrzejewski/configuration-server
          ports:
            - containerPort: 8888
              name: http
          envFrom:
            - configMapRef:
                name: base
          livenessProbe:
            periodSeconds: 1800
            failureThreshold: 3
            initialDelaySeconds: 10
            httpGet:
              port: 8888
              path: /05-Kubernetes/application-default.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-service
spec:
  selector:
    app-name: configuration
  ports:
    - port: 8888
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
spec:
  replicas: 3
  selector:
    matchLabels:
      app-name: discovery
  template:
    metadata:
      labels:
        app-name: discovery
    spec:
      containers:
        - name: configuration
          image: landrzejewski/discovery-server
          ports:
            - containerPort: 8089
              name: http
          envFrom:
            - configMapRef:
                name: base
          livenessProbe:
            periodSeconds: 1800
            failureThreshold: 3
            initialDelaySeconds: 10
            httpGet:
              port: 8089
              path: /swagger-ui.html
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app-name: discovery
  ports:
    - port: 8089
      targetPort: http