apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-server-rc
spec:
  replicas: 2
  selector:
    matchLabels:
      app-name: web-server-app
  template:
    metadata:
      labels:
        app-name: web-server-app
    spec:
      containers:
        - image: nginx:1.17.3-alpine
          name: web-server
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app-name: web-server-app
  ports:
    - port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /echo
            backend:
              serviceName: echo-service
              servicePort: 80
          - path: /web/(.*)
            backend:
              serviceName: web-server-service
              servicePort: 80