apiVersion: v1
kind: ConfigMap
metadata:
  name: updater-cm
data:
  INTERVAL: '20'
  sleepInterval: '15'
  version: v1
  2: '5'
---
apiVersion: v1
kind: Pod
metadata:
  name: updater-po
spec:
  containers:
    - name: updater
      image: landrzejewski/updater:v2

      # set cmd args
      #args:
      #  - '20'

      # set env directly
      #env:
      # - name: INTERVAL
      #     value: '20'

      # set env from config map
      #env:
      #  - name: INTERVAL
      #    valueFrom:
      #       configMapKeyRef:
      #         name: updater-cm
      #         key: sleepInterval

      envFrom:
        - configMapRef:
           name: updater-cm

      volumeMounts:
        - mountPath: /var/htdocs
          name: storage
        - mountPath: /config
          name: config
    - name: web-server
      image: nginx:1.17.3-alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: storage
      ports:
        - containerPort: 80
  volumes:
    - name: storage
      hostPath:
        path: /tmp/storage
    - name: config
      configMap:
        name: updater-cm